image: maven:3.5.0-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  JACOCO_AGENT:   "target/coverage/jacoco.exec"

stages:
  - build
  - test
  - qa
  - deploy

cache:
  paths:
    - .m2/repository
    - target/

build_job:
  stage: build
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true

test_unit:
 stage: test
 script:
   - mvn test -P Unit

test_isolation:
 stage: test
 script:
   - mvn test -P Isolation

test_integration:
 stage: test
 script:
   - mvn test -P Integration

test_sequence:
 stage: test
 script:
   - mvn test -P Sequence
