image: maven:3.5.0-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  JACOCO_AGENT:   "target/coverage/jacoco.exec"

stages:
  - build
  - test
  - qa
  - deploy

cache:
  paths:
    - .m2/repository
    - target/

build_job:
  stage: build
  script:
    - mvn --batch-mode compile -Dmaven.test.skip=true -Djacoco.skip=true

test_unit:
 stage: test
 script:
   - mvn test -P Unit

test_isolation:
 stage: test
 script:
   - mvn test -P Isolation

test_integration:
 stage: test
 script:
   - mvn test -P Integration

test_sequence:
 stage: test
 script:
   - mvn test -P Sequence

sonar_publish_job:
  stage: qa
  before_script:
    - mvn -Djacoco.destFile=$JACOCO_AGENT clean org.jacoco:jacoco-maven-plugin:0.7.8:prepare-agent install
    - mvn -X -Djacoco.dataFile=$JACOCO_AGENT -Djacoco.outputDirectory=./jacoco_ut org.jacoco:jacoco-maven-plugin:report
  script:
    - mvn --batch-mode verify jxr:jxr pmd:pmd sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_USER_TOKEN -Dsonar.analysis.mode=publish -Dsonar.issuesReport.console.enable=true -Dsonar.jacoco.reportPath=$JACOCO_AGENT -Dsonar.junit.reportPaths=target/surefire-reports
  coverage: /Total.*?([0-9]{1,3})%/

pages:
  stage: deploy
  script:
    - mvn install site
    - mkdir .public
    - cp -R target/site/* .public
    - rm -rf .public/xref
    - rm -rf .public/xref-test
    - mv .public public
  artifacts:
    paths:
      - public
    expire_in: 30 days
